name: Nick Tyrrell
favicon: null
layout_spectrum: 0.49578137043863535
typography_spectrum: 0.016177474753931165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7593283655587584
  lightness: 0.6003078401554376
  saturation: 0.5461554063949734
  rhythmicContrast: 0.11584128369577229
purpose: []
